# Site settings
title: The Learning Plumber
description: > # this means to ignore newlines until "baseurl:"
  This is the blog site of Zhongzhou Chen, a college physics teacher and a physics education researher
  who calls himself a "learning plumber" 
#I don't think I need those settings for now, CoPilot worte those for me.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://myawesomesite.com" # the base hostname & protocol for your site

# Build settings

theme: minima #(this was the default)
#trying this remote theme
#remote_theme: pages-themes/cayman@v0.2.0

 
#plugins:
#- jekyll-remote-theme # this is needed if I want to switch to some remote theme

markdown: kramdown
#I don't know what those are doing as of now.
#permalink: pretty

# Author settings
author: Zhongzhou Chen
  #email: blackeyemickey at gmail.com
  
