# Site settings
title: The Learning Plumber
description: > # this means to ignore newlines until "baseurl:"
  This is the blog site of Zhongzhou Chen, a college physics teacher and a physics education researher
  who calls himself a "learning plumber" 
#I don't think I need those settings for now, CoPilot worte those for me.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://myawesomesite.com" # the base hostname & protocol for your site

# Build settings
theme: minima

#I don't know what those are doing as of now.
#markdown: kramdown
#permalink: pretty

# Author settings
author: Zhongzhou Chen
  #email: blackeyemickey@gmail.com
